### ISSUE TITLE
Latest update busted gulp

### ISSUE THREAD

**Issue by allthefoxes** [honestbleeps/Reddit-Enhancement-Suite#2016]
[13:32:37] Using gulpfile ~/Reddit-Enhancement-Suite/gulpfile.js
    [13:32:37] Starting 'clean'...
    [13:32:37] Finished 'clean' after 4.61 ms
    [13:32:37] Starting 'default'...
    [13:32:37] Starting 'module-css-chrome'...
    [13:32:37] 'module-css-chrome' errored after 5.39 ms
    [13:32:37] TypeError: object is not a function
        at Gulp.gulp.task.gulp.src.pipe.imagemin.optimizationLevel (/home/ec2-user/Reddit-Enhancement-Suite/gulpfile.js:109:19)
        at module.exports (/home/ec2-user/Reddit-Enhancement-Suite/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
        at Gulp.Orchestrator._runTask (/home/ec2-user/Reddit-Enhancement-Suite/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
        at Gulp.Orchestrator._runStep (/home/ec2-user/Reddit-Enhancement-Suite/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
        at Gulp.Orchestrator.start (/home/ec2-user/Reddit-Enhancement-Suite/node_modules/gulp/node_modules/orchestrator/index.js:134:8)
        at Gulp.buildDir (/home/ec2-user/Reddit-Enhancement-Suite/gulpfile.js:15:7)
        at module.exports (/home/ec2-user/Reddit-Enhancement-Suite/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
        at Gulp.Orchestrator._runTask (/home/ec2-user/Reddit-Enhancement-Suite/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
        at Gulp.Orchestrator._runStep (/home/ec2-user/Reddit-Enhancement-Suite/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
        at /home/ec2-user/Reddit-Enhancement-Suite/node_modules/gulp/node_modules/orchestrator/index.js:279:18
    [13:32:37] Finished 'default' after 9.86 ms

Note that 'modules-css-chrome' is always the first task that happens, it doesn't necessarily mean *that* is the broken task

**Comment by allthefoxes** [comment]
I really can't see anything causing this, and I am thinking this might just be my node js acting up again
