### ISSUE TITLE
gulp clean is failing

### ISSUE THREAD

**Issue by mc10** [honestbleeps/Reddit-Enhancement-Suite#2559]
I'm getting the following error:
```
[16:43:33] Failed to load external module babel/register
[etc]/Reddit-Enhancement-Suite/gulpfile.babel.js:3
import gulp from 'gulp';
^^^^^^

SyntaxError: Unexpected token import
    at exports.runInThisContext (vm.js:54:16)
    at Module._compile (module.js:375:25)
    at Object.Module._extensions..js (module.js:406:10)
    at Module.load (module.js:345:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:355:17)
    at require (internal/module.js:13:17)
    at Liftoff.handleArguments (/usr/local/lib/node_modules/gulp/bin/gulp.js:116:3)
    at Liftoff.<anonymous> (/usr/local/lib/node_modules/gulp/node_modules/liftoff/index.js:192:16)
    at module.exports (/usr/local/lib/node_modules/gulp/node_modules/liftoff/node_modules/flagged-respawn/index.js:17:3)
```

This is with a completely clean `node_modules` and a fresh `npm install` afterwards.

**Comment by mc10** [comment]
Hmm reinstalling global `gulp` seemed to fix the problem. I'll leave a note in the `README`.
