### ISSUE TITLE
XHR Error with multiple media host expandos

### ISSUE THREAD

**Issue by BenMcGarry** [honestbleeps/Reddit-Enhancement-Suite#3985]
```
showImages: could not create expando for https://en.wikipedia.org/wiki/Oxygen_toxicity
main.entry.js (76890,7)


Error: Error in target's "ajax" handler: XHR error - url: https://en.wikipedia.org/w/api.php?action=parse&format=json&prop=text|displaytitle&section=0&page=Oxygen_toxicity&origin=*
main.entry.js (76891,7)
   {
      [functions]: ,
      __proto__: { },
      description: "Error in target's "ajax" handler: XHR error - url: https://en.wikipedia.org/w/api.php?action=parse&format=json&prop=text|displaytitle&section=0&page=Oxygen_toxicity&origin=*",
      message: "Error in target's "ajax" handler: XHR error - url: https://en.wikipedia.org/w/api.php?action=parse&format=json&prop=text|displaytitle&section=0&page=Oxygen_toxicity&origin=*",
      name: "Error",
      stack: "Error: Error in target's "ajax" handler: XHR error - url: https://en.wikipedia.org/w/api.php?action=parse&format=json&prop=text|displaytitle&section=0&page=Oxygen_toxicity&origin=*
   at _handleMessage (main.entry.js:4673:6)
   at Anonymous function (main.entry.js:4488:5)"
   }
```

**Comment by larsjohnsen** [comment]
This is fairly common for Wikipedia expandos, so I doubt there's something Edge specific about this.

**Comment by BenMcGarry** [comment]
Issue non-repo in Edge 14 but repro in Edge 15.

**Comment by BenMcGarry** [comment]
This is due to "Enable XMLHttpRequests over Fetch" being enabled on builds. Disabling resolves.

**Comment by BenMcGarry** [comment]
```
Error: XHR error - url: https://en.wikipedia.org/w/api.php?action=parse&format=json&prop=text|displaytitle&section=0&page=Tillingdale&origin=*
messaging.js (35,124)
   {
      [functions]: ,
      __proto__: {
         [functions]: ,
         __proto__: {
            [functions]: ,
            __proto__: null
         },
         message: "",
         name: "Error"
      },
      description: "XHR error - url: https://en.wikipedia.org/w/api.php?action=parse&format=json&prop=text|displaytitle&section=0&page=Tillingdale&origin=*",
      message: "XHR error - url: https://en.wikipedia.org/w/api.php?action=parse&format=json&prop=text|displaytitle&section=0&page=Tillingdale&origin=*",
      name: "Error",
      stack: "Error: XHR error - url: https://en.wikipedia.org/w/api.php?action=parse&format=json&prop=text|displaytitle&section=0&page=Tillingdale&origin=*
   at Anonymous function (ms-browser-extension://EdgeExtension_37237honestbleepsRedditEnhancementSuite_jzcrwe0958h6m/background.entry.js:47512:4)"
   }

```

**Comment by BenMcGarry** [comment]
https://github.com/honestbleeps/Reddit-Enhancement-Suite/blob/cc69963d71033325b8847ff55821c83385c17ae6/lib/environment/ajax.js#L85

https://github.com/honestbleeps/Reddit-Enhancement-Suite/blob/6bbb6a53355be22ee0558418c43ad4d236a90fed/chrome/background.entry.js#L67-L86

**Comment by BenMcGarry** [comment]
Issue is now being tracked by Microsoft.

**Comment by BenMcGarry** [comment]
Re-opened to track for fix on Edge releases.

**Comment by erikdesjardins** [comment]
Tes extension: https://gist.github.com/erikdesjardins/1026a90f87ef3b93fa4f4bd2e59d2314
