### ISSUE TITLE
Cannot run Ava unit tests on Node v.6.11.0 LTS

### ISSUE THREAD

**Issue by jkayani** [honestbleeps/Reddit-Enhancement-Suite#4318]
- My browser (copy from https://www.whatismybrowser.com): Chrome 59 on Linux
- My RES version: Development version from Github, commit d3f3779819692d345277cc869c4b6134166534f7
- Am I in reddit beta (yes/no): no

*What's the problem?*
After following the instructions mentioned on the [CONTRIBUTING.md](https://github.com/honestbleeps/Reddit-Enhancement-Suite/blob/master/CONTRIBUTING.md) page, I am unable to run the unit tests using `npm test`. I get the following stack trace(s):

````
josh@Josh-Dell:~/Github/Reddit-Enhancement-Suite$ npm test

> reddit-enhancement-suite@5.7.3 test /home/josh/Github/Reddit-Enhancement-Suite
> cross-env NODE_ENV=test ava

/home/josh/Github/Reddit-Enhancement-Suite/browser/utils/__tests__/messaging.js:64
(0, _ava2.default)('backend handler', async t => {
                                      ^^^^^
SyntaxError: missing ) after argument list
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at extensions.(anonymous function) (/home/josh/Github/Reddit-Enhancement-Suite/node_modules/require-precompiled/index.js:13:11)
    at Object.require.extensions.(anonymous function) [as .js] (/home/josh/Github/Reddit-Enhancement-Suite/node_modules/ava/lib/process-adapter.js:100:4)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/josh/Github/Reddit-Enhancement-Suite/node_modules/ava/lib/test-worker.js:49:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
/home/josh/Github/Reddit-Enhancement-Suite/lib/utils/__tests__/array.js:26
(0, _ava2.default)('forEachSeq', async t => {
                                 ^^^^^
SyntaxError: missing ) after argument list
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at extensions.(anonymous function) (/home/josh/Github/Reddit-Enhancement-Suite/node_modules/require-precompiled/index.js:13:11)
    at Object.require.extensions.(anonymous function) [as .js] (/home/josh/Github/Reddit-Enhancement-Suite/node_modules/ava/lib/process-adapter.js:100:4)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/josh/Github/Reddit-Enhancement-Suite/node_modules/ava/lib/test-worker.js:49:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
/home/josh/Github/Reddit-Enhancement-Suite/lib/utils/__tests__/async.js:29
(0, _ava2.default)('waitFor - basic', async t => {
                                      ^^^^^
SyntaxError: missing ) after argument list
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at extensions.(anonymous function) (/home/josh/Github/Reddit-Enhancement-Suite/node_modules/require-precompiled/index.js:13:11)
    at Object.require.extensions.(anonymous function) [as .js] (/home/josh/Github/Reddit-Enhancement-Suite/node_modules/ava/lib/process-adapter.js:100:4)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/josh/Github/Reddit-Enhancement-Suite/node_modules/ava/lib/test-worker.js:49:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
Could not parse: foo falling back to raw string.
````
I am using Node.js LTS, v. 6.11. Supposedly, the above issue is because:

<blockquote>
async/await are not transpiled using the preset es2015.
You should enable the preset es2017 or latest.
Another solution is to run your test suite on Node v7 since it natively support async/await.
</blockquote>

This is where I found that information: http://techqa.info/programming/question/40258394/Ava-js-not-working-async-await-tests. I'd open a PR about this, but I am unsure which config files need to be changed, and do not want to break the build process.

Anyway, CONTRIBUTING.md says that any version of node >= 6 can be used to build the extension, but this doesn't appear to be the case. I have since upgraded to Node v.8.1.2 and am able to run the tests with no errors. 

*Are there any related posts in https://github.com/honestbleeps/Reddit-Enhancement-Suite/issues or /r/RESissues?*
No.

*What other browser extensions are installed?*
UBlock Origin, LastPass

**Comment by erikdesjardins** [comment]
Yep, you will need Node 7.6/8 to run unit tests. Everything else should work in 6 though (and even 4 last time I checked).

I'll add a note to that command, but most people will never need to run unit tests, so we won't require it up-front.
